gmooc/apps/courses/urls.py
from django.urls import path

from .views import CourseListView, CourseDetailView, CourseLessonView, CourseCommentView, AddCommentView, VideoPlayView

app_name = "course"
urlpatterns = [
    path("list/", CourseListView.as_view(), name="course_list"),
    path("detail/<int:course_id>/", CourseDetailView.as_view(), name="course_detail"),
    path("lesson/<int:course_id>/", CourseLessonView.as_view(), name="course_lesson"),
    path("comment/<int:course_id>/", CourseCommentView.as_view(), name="course_comment"),
    path("add_comment/", AddCommentView.as_view(), name="add_comment"),
    path("video/<int:video_id>/", VideoPlayView.as_view(), name="video_play"),
]

gmooc/apps/organizations/urls.py
from django.urls import path

from .views import OrgListView, UserAskView, OrgDetailView, OrgDescView, OrgCourseView, OrgTeacherView, AddFavView
from .views import TeacherListView, TeacherDetailView

app_name = "org"
urlpatterns = [
    path('list/', OrgListView.as_view(), name="org_list"),
    path('add_ask/', UserAskView.as_view(), name="add_ask"),
    path('org_home/<int:org_id>/', OrgDetailView.as_view(), name="org_home"),
    path('org_course/<int:org_id>/', OrgCourseView.as_view(), name="org_course"),
    path('org_desc/<int:org_id>/', OrgDescView.as_view(), name="org_desc"),
    path('org_teacher/<int:org_id>/', OrgTeacherView.as_view(), name="org_teacher"),
    path('add_fav/', AddFavView.as_view(), name="add_fav"),
    path('teacher/list/', TeacherListView.as_view(), name="teacher_list"),
    path('teacher/detail/<int:teacher_id>', TeacherDetailView.as_view(), name="teacher_detail"),
]

gmooc/apps/users/urls.py
from django.urls import path

from .views import UserInfoView, UploadImageView, UserModifyPwdView, SendEmailCodeView, ModifyEmailView
from .views import MyCourseView, MyFavView, MyMessageView


app_name = 'users'
urlpatterns = [
    path('info/', UserInfoView.as_view(), name="users_info"),
    path('upload_image/', UploadImageView.as_view(), name="upload_image"),
    path('modify_pwd/', UserModifyPwdView.as_view(), name="modify_pwd"),
    path('send_email_code/', SendEmailCodeView.as_view(), name="send_email_code"),
    path('modify_email/', ModifyEmailView.as_view(), name="modify_email"),
    path('mycourse/', MyCourseView.as_view(), name="mycourse"),
    path('my_fav/', MyFavView.as_view(), name="my_fav"),
    path('message/', MyMessageView.as_view(), name="message")
]

gmooc/extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

gmooc/gmooc/urls.py
import xadmin

from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from gmooc import settings
from users.views import IndexView, LoginView, LogoutView, RegisterView, ActiveUserView, ForgetPwdView, PwdResetView, PwdModifyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('', IndexView.as_view(), name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('captcha/', include('captcha.urls')),
    path('active/<active_code>/', ActiveUserView.as_view(), name="user_active"),
    path('forget/', ForgetPwdView.as_view(), name="forget_pwd"),
    path('reset/<code>', PwdResetView.as_view(), name="reset"),
    path('pwd_reset/', PwdModifyView.as_view(), name="reset_pwd"),

    # 课程机构url配置
    path('org/', include('organizations.urls', namespace='org')),
    path('course/', include('courses.urls', namespace='course')),
    path('users/', include('users.urls', namespace='users')),

    # media上传文件url处理
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
    # re_path(r'^static/(?P<path>.*)$', serve, {
        # 'document_root': settings.STATIC_ROOT,
    # }),

    path('ueditor/', include('DjangoUeditor.urls'))
]

# 默认处理函数的template_name为404.html 和 500.html，只需配置html文件
# handler404 = 'users.views.not_found_page'
# handler500 = 'users.views.internal_error'

gmooc/extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

gmooc/templates/active_fail.html
<!DOCTYPE html>
<html>
  <body>
  验证失败
  </body>
</html>

gmooc/templates/org-base.html
<!DOCTYPE html>
<html>
  {% load static %}
  <head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>{% block title %}机构首页{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}{% endblock %}
  </head>
  <body>
    <section class="headerwrap headerwrap2">
      <header>
        <div  class="header2 header">

          {% if request.user.is_authenticated %}
          <div class="top">
            <div class="wp">
              <div class="fl"><p>服务电话：<b>33333333</b></p></div>
              <!--登录后跳转-->
              <div class="personal">
                <dl class="user fr">
                  <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                  <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                </dl>
                <div class="userdetail">
                  <dl>
                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                    <dd>
                    <h2>django</h2>
                    <p>{{ request.user.username }}</p>
                    </dd>
                  </dl>
                  <div class="btn">
                    <a class="personcenter fl" href="{% url 'users:users_info'%}">进入个人中心</a>
                    <a class="fr" href="{% url 'logout' %}">退出</a>
                  </div>
                </div>
              </div>
              <a href="{% url 'users:message' %}">
                  <div class="msg-num"><span id="MsgNum">{{ request.user.get_unread_msg_nums }}</span></div>
              </a>
            </div>
          </div>
          {% else %}
          <div class="top">
            <div class="wp">
              <div class="fl"><p>服务电话：<b>33333333</b></p></div>
              <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
              <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
            </div>
          </div>
          {% endif %}

          <div class="middle companyheader">
            <div class="wp">
                <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
              <div class="head fl">
                <h1>
                    {{ course_org.name }}
                  <img src="{% static 'images/authentication.png' %}"/>
                  <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                <span class="precision company-credit" data-star-scope="5.0"></span>
                <span class="key">5.0</span>
                </p>
              </div>
              <div class="btn fr collectionbtn  notlogin" data-favid="{{ course_org.id }}" data-fav-type="1">
                  {% if has_fav %}已收藏{% else %}收藏{% endif %}
             </div>

            </div>
          </div>
        </div>
      </header>
    </section>
    <section>
      <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
          <li>{% block page_path %}机构首页{% endblock %}</li>
        </ul>
      </div>
    </section>

    <section>
      <div class="wp list personal_list comp">
        <div class="left">
            <ul>
                <li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">机构讲师</a></li>
          </ul>
        </div>

        {% block right_form %}
        {% endblock %}


    </section>
    <!--sidebar start-->
    <section>
      <ul class="sidebar">
        <li class="qq">
          <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
      </ul>
    </section>
    <!--sidebar end-->
    <!--header start-->
      </div>
      <!--弹出省省市-->
      <script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
      <script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
      <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
      <script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

      <script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
      <script type="text/javascript">
        //收藏分享
        function add_fav(current_elem, fav_id, fav_type){
          $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'org:add_fav' %}",
            data:{'fav_id':fav_id, 'fav_type':fav_type},
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                console.log(data)
              if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="{% url 'login' %}";
                }else{
                  alert(data.msg)
                }

              }else if(data.status == 'success'){
                current_elem.text(data.msg)
              }
            },
          });
        }
        $('.collectionbtn').on('click', function(){
            add_fav($(this), {{ course_org.id }}, 2);
        });

        $(function(){
          var $precision = $('.precision'),
          score = $precision.attr('data-star-scope'),
          option =  {
            half		: true,
            path		: '{% static "images/" %}',
            precision	: true,
            size		: 24,
            starOff		: 'g_star.png',
            starOn		: 'r_star.png',
            starHalf	: 'h_star.png',
            hints       : ['极差', '差', '一般', '好评', '非常满意'],
            noRatedMsg  : '暂时还未获得评价！',
            readOnly    : true,
            score       : score
          };
          $precision.raty(option);

          $('.jsFavBtn').on('click', function(){
          var type = $(this).attr('data-fav-type');
          if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

          }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

          }else if(type == '11'){
            favPraise($(this), 'pra', 1);

          }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

          }
        });
      })
      </script>

      <script type="text/javascript">
          $(function(){
              $('.header .personal').hover(function(){
                  $('.header .userdetail').stop(true).show();
              },function(){
                  $('.header .userdetail').stop(true).hide();
              });
          })
      </script>

      <!-- <script type="text/javascript"> -->
        <!-- $(function() { -->
          <!-- $('.recordbtn1').click(function(){ -->
            <!-- $('.recordbox1').show(); -->
          <!-- }); -->
          <!-- $('.recordbtn2').click(function(){ -->
            <!-- $('.recordbox2').show(); -->
          <!-- }); -->

          <!-- $('.imgslide').unslider({ -->
            <!-- speed: 500,               //  The speed to animate each slide (in milliseconds) -->
            <!-- delay: 3000,              //  The delay between slide animations (in milliseconds) -->
            <!-- complete: function() {},  //  A function that gets called after every slide animation -->
            <!-- keys: true,               //  Enable keyboard (left, right) arrow shortcuts -->
            <!-- dots: true,               //  Display dot navigation -->
            <!-- fluid: false              //  Support responsive design. May break non-responsive designs -->
          <!-- }); -->
          <!-- var unslider = $('.imgslide').unslider(); -->
          <!-- $('.unslider-arrow').click(function() { -->
            <!-- var fn = this.className.split(' ')[1]; -->
            <!-- unslider.data('unslider')[fn](); -->
          <!-- }); -->
        <!-- }); -->
      <!-- </script> -->

  </body>
</html>

gmooc/templates/teacher-detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
讲师列表 - 慕学在线网
{% endblock %}

{% block header %}
<nav>
  <div class="nav">
    <div class="wp">
      <ul>
        <li ><a href="{% url 'index' %}">首页</a></li>
        <li >
          <a href="{% url 'course:course_list' %}">
            公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
          </a>
        </li>
        <li class="active" >
          <a href="{% url 'org:teacher_list' %}">授课教师</a>
        </li>
        <li ><a href="{% url 'org:org_list' %}">授课机构</a></li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}

{% block custom_bread %}
<section>
  <div class="wp">
    <ul  class="crumbs">
      <li><a href="{% url 'index' %}">首页</a>></li>
      <li>课程讲师</li>
    </ul>
  </div>
</section>
{% endblock %}

{% block custom_js %}
<script type="text/javascript">
  //收藏分享
  function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
      cache: false,
      type: "POST",
      url:"{% url 'org:add_fav' %}",
      data:{'fav_id':fav_id, 'fav_type':fav_type},
      async: true,
      beforeSend:function(xhr, settings){
        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
      },
      success: function(data) {
        if(data.status == 'fail'){
          if(data.msg == '用户未登录'){
            window.location.href="{% url 'login' %}";
          }else{
            alert(data.msg)
          }

        }else if(data.status == 'success'){
          current_elem.text(data.msg)
        }
      },
    });
  }

$('#jsLeftBtn').on('click', function(){
  add_fav($(this), {{ teacher.id }}, 3);
});

$('#jsRightBtn').on('click', function(){
  add_fav($(this), {{ teacher.org.id }}, 2);
});
</script>
{% endblock %}


{% block content %}
<section>
  <div class="wp butler-detail-box butler-diaryd-box clearfix">
    <div class="fl list">
      <div class="butler_detail_list clearfix">
        <div class="brief">
          <dl class="des">
            <dt>
            <div class="picpic">
              <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
            </div>
            <div class="btn">
              <span class="fl btn1 collectionbtn" id="jsLeftBtn">
                {% if has_fav_teacher %}已收藏{% else %}收藏{% endif %}
              </span>
              <span class="fr btn2 shareBtn bdsharebuttonbox"
                    data-text="授课教师-李老师-慕学网"
                    data-desc="我在#慕课网#发现了"
                    data-comment="李老师，工作年限：5年；学历：本科；所在公司：阿里巴巴&nbsp;；经典案例：django入门和深入；flask入门"
                    data-url="/diary/hk_detail/10/">
                <span class="fl">分享</span>
                <a href="#" class="bds_more" data-cmd="more"></a>
              </span>
            </div>
            </dt>
            <dd>
            <a href="{% url 'org:teacher_detail' teacher.id %}">
              <h1>{{ teacher.name }}<span class="key picbig">金牌讲师</span></h1>
            </a>
            <ul class="cont">
              <li>工作年限：<span>{{ teacher.work_years }}</span></li>
              <li>就职公司：<span>{{ teacher.work_company }}</span></li>
              <li>工作职位：<span>{{ teacher.work_position }}&nbsp;</span></li>
              <li>教学特点：<span>{{ teacher.feature }}</span></li>
            </ul>
            </dd>
          </dl>
        </div>
      </div>
      <div class="butler_detail_cont clearfix">
        <div class="left layout">
          <div class="head">
            <ul class="tab_header">
              <li class="active"><a href="/diary/hk_detail/10/">全部课程</a> </li>
            </ul>
          </div>
          <div class="companycenter">
            <div class="group_list brief">
              {% for course in teacher_courses.object_list %}
              <div class="module1_5 box">
                <a href="course-detail.html">
                  <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                </a>
                <div class="des">
                  <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                  <span class="fl">时长：<i class="key">{{ course.learn_time }}</i></span>
                  <span class="fr">学习人数：{{ course.students }}</span>
                </div>
                <div class="bottom">
                  <span class="fl">{{ course.course_org }}</span>
                  <span class="star fr  notlogin" data-favid="15">{{ course.fav_nums }}</span>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          <div class="pageturn">
              <ul class="pagelist">
                  {% if teacher_courses.has_previous %}
                      <li class="long"><a href="?{{ all_orgs.previous_page_number.querystring }}">上一页</a></li>
                  {% endif %}
                  {% for page in teacher_courses.pages %}
                      {% if page %}
                          {% ifequal page teacher_courses.number %}
                              <li class="active">{{ page }}</li>
                          {% else %}
                              <li class="page"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                          {% endifequal %}
                      {% else %}
                          <li><a href="" class="page">...</a></li>
                      {% endif %}
                  {% endfor %}
                  {% if teacher_courses.has_next %}
                      <li class="long"><a href="?{{ all_orgs.previous_page_number.querystring }}">上一页</a></li>
                  {% endif %}
              </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="fr list">
      <div class="butler_detail_list">
        <div class="right butler-company-box">
          <div class="head">
            <h1>{{ teacher.org.name }}</h1>
            <p>知名高校，权威教学</p>
          </div>
          <div class="pic">
            <a href="{% url 'org:org_home' teacher.org.id %}">
              <img width="150" height="80" src="{{ MEDIA_URL }}{{ teacher.org.image }}"/>
            </a>
          </div>
          <a href="{% url 'org:org_home' teacher.org.id %}">
            <h2 class="center">{{ teacher.org.name }}</h2>
          </a>
          <p class="center tell">地址：{{ teacher.org.address }}</p>
          <a class="btn" id="jsRightBtn">
              {% if has_fav_org %}已收藏{% else %}收藏{% endif %}
          </a>
        </div>
      </div>
      <div class="butler_detail_cont">
        <div class="butler_list_box">
          <div class="right layout">
            <div class="head">讲师排行榜</div>

            {% for teacher in hot_teachers %}
            <dl class="des">
                <span class="num fl">1</span>
                <a href="{% url 'org:teacher_detail' teacher.id %}">
                    <dt>
                    <img width="50" height="50" class="scrollLoading"  src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                    </dt>
                </a>
                <dd>
                <a href="{% url 'org:teacher_detail' teacher.id %}">
                    <h1 title="bobby">{{ teacher.name }}</h1>
                </a>
                <p>工作年限：<span>{{ teacher.work_years }}</span></p>
                </dd>
            </dl>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}